{{ if and .Values.secret .Values.secret.TS_AUTHKEY -}}
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-secret
  namespace: {{ .Release.Namespace }}
stringData:
  TS_AUTHKEY: {{ .Values.secret.TS_AUTHKEY }}
  TS_ROUTES: {{ .Values.secret.TS_ROUTES }}
  TS_EXTRA_ARGS: {{ .Values.secret.TS_EXTRA_ARGS }}
{{- end -}}